export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_USER_DATA = 'GET_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const ADD_USER_DATA = 'ADD_USER_DATA';
export const GET_USERS_FROM_GROUP = 'GET_USERS_FROM_GROUP';
export const ERROR = 'ERROR';
export const GET_TASKS_LIST = 'GET_TASKS_LIST';